const escapeHtml = (s) => String(s === null || s === undefined ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

function getYearFromPayload(p) {
  if (!p) return (new Date()).getFullYear();
  const cand = p.year || p.yr || (p.date && String(p.date).slice(0,4));
  const n = parseInt(cand, 10);
  if (!isNaN(n) && n > 1900 && n < 3000) return n;
  return (new Date()).getFullYear();
}

function generatedByFooterHtml(payload) {
  const year = getYearFromPayload(payload && payload.payload ? payload.payload : payload);
  const appName = 'Bravo Food Safety Management App';
  return `\n<div style="width:100%; text-align:right; font-size:16px; color:#111; margin-top:16px; padding-top:8px; border-top:1px solid #E5E7EB; font-weight:700">Generated by ${escapeHtml(appName)} · ${escapeHtml(String(year))}</div>\n`;
}

function injectFooterIntoHtml(html, payload) {
  if (!html || typeof html !== 'string') return html;
  const footer = generatedByFooterHtml(payload);
  const re = /<\/body>\s*<\/html>\s*$/i;
  if (re.test(html)) return html.replace(re, footer + '</body></html>');
  // fallback: append
  return html + '\n' + footer;
}

module.exports = { generatedByFooterHtml, injectFooterIntoHtml };
